# Generated by Django 4.1.3 on 2023-02-02 02:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expAI', '0012_user_chose_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model_trained',
            fields=[
                ('model_trainedid', models.AutoField(db_column='model_trainedID', primary_key=True, serialize=False)),
                ('model_trainedcreatedtime', models.DateTimeField(blank=True, db_column='model_trainedCreatedTime', null=True)),
                ('model_trainedconfigid', models.ForeignKey(blank=True, db_column='model_trainedConfigID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='expAI.paramsconfigs')),
                ('model_trainedcreatorid', models.ForeignKey(blank=True, db_column='model_trainedCreatorID', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('modelid', models.ForeignKey(blank=True, db_column='modelID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='expAI.models')),
            ],
            options={
                'db_table': 'Model_trained',
                'managed': True,
            },
        ),
    ]
