# Generated by Django 4.1.3 on 2023-02-07 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expAI', '0013_model_trained'),
    ]

    operations = [

    ]
