# Generated by Django 4.1.3 on 2023-03-30 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expAI', '0014_model_trained_model_trainedexpid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='usrclass',
            field=models.CharField(blank=True, db_column='usrClass', max_length=45, null=True),
        ),
    ]
