# Generated by Django 4.1.3 on 2023-04-21 23:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expAI', '0015_user_usrclass'),
    ]

    operations = [

        migrations.AddField(
            model_name='models',
            name='modelowner',
            field=models.ForeignKey(blank=True, db_column='modelowner', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
